checks:
  php: true

build:
  environment:
    php:
      version: 7.4

  nodes:
    phpunit:
      environment:
        timezone: Europe/Amsterdam
        postgresql: false
        rabbitmq: false
        mysql: false
        redis: false
        elasticsearch: false
        php:
          version: 7.4
      tests:
        override:
          - command: 'vendor/bin/phpunit --coverage-clover=code-coverage'
            coverage:
              file: 'code-coverage'
              format: 'clover'

    analysis:
      environment:
        postgresql: false
        redis: false
        mongodb: false
        mysql: false
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run

  dependencies:
    override:
      - command: 'composer install --no-interaction --no-scripts'

filter:
  excluded_paths:
    - 'tests/*'
